######################################################################
# Automatically generated by qmake (2.01a) ?? 6? 2 00:13:34 2019
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += ui_untitled.h
SOURCES += t.cpp
